name: intercom_flutter_platform_interface
description: A common platform interface for the intercom_flutter plugin.
version: 1.0.0
homepage: https://github.com/v3rm0n/intercom_flutter

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.4

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  mockito: ^5.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.22.0"
